-- ******** QUERIES ON EMPLOYEES TABLE *************

-- 1 Counts Number of employees in each department
select department_id, count(*) total_emp from hr.EMPLOYEES group by DEPARTMENT_ID;

-- 2 Calculates avg sal in each department
select department_id, avg(salary) avg_salary from hr.EMPLOYEES group by DEPARTMENT_ID;

-- 3 Returns max and min sal of each dept
select department_id, min(salary) min_salary, max(salary) max_salary from hr.employees group by DEPARTMENT_ID;

-- 4 sums up all employee salaries in each department.
select department_id, sum(salary) _total_salary from hr.employees group by DEPARTMENT_ID;

-- 5 counts num of emp in each job role
select JOB_ID, count(*) job_role_nums from hr.employees group by job_id;

-- 6 finds avg sal for each job role
select job_id, avg(salary) avg_salary from hr.employees group by job_id;

-- 7,8,9 finds max sal , min sal, sum or total sal for each job id 
select job_id, max(salary) max_salary, min(salary) min_salary, sum(salary) total_salary from hr.employees group by job_id;

-- 10 extracts year and give num of emp hired in each year
select EXTRACT(year from hire_date) years, count(*) no_of_emp from hr.EMPLOYEES group by extract(year from hire_date) order by years;

-- 11 sums up the total salary per location by joining employees with department locations
select departments.location_id,sum(employees.salary) from hr.EMPLOYEES join hr.DEPARTMENTS on employees.location_id = DEPARTMENTS.location_id group by departments.location_id;

-- 12 counts the employees who report to each manager and manager id is not null
select manager_id, count(*) no_of_emp from hr.EMPLOYEES where manager_id IS NOT NULL group by MANAGER_ID;

-- 13,14 finds the highest salary and avg sal among employees reporting to each manager.
select manager_id, max(salary) max_sal,avg(salary) avg_sal from hr.employees where MANAGER_ID IS NOT NULL group by MANAGER_ID;

-- 15 extracts the month from hire_date and counts how many employees were hired in each month.
select extract(month from hire_date) months,count(*) total_emp from hr.employees group by extract(month from hire_date) order by months;

-- 16 finds the department that pays the highest total salary by sorting in descending order.
select department_id, sum(salary) _total_salary from hr.employees group by department_id order by total_salary DESC FETCH FIRST 1 ROW ONLY;

-- 17 finds the job role with the highest average salary by sorting in descending order.
select job_id, avg(salary) avg_salary from hr.employees group by job_id order by avg_salary DESC FETCH FIRST 1 ROW ONLY;

-- 19  counts employees who receive a commission, grouped by department.
select department_id, count(*) total_emp from hr.EMPLOYEES where commission_pct IS NOT NULL group by department_id;

-- 20 sums up the salaries of employees who receive a commission, grouped by department.
select department_id, sum(salary) total_sal from hr.employees where commission_pct IS NOT NULL group by department_id; 


-- ********** QUERIES ON SALES TABLE ***************

-- 1 Counts the number of sales transactions for each product.
select product_id, count(*) total_sales from sh.sales group by product_id;

-- 2 calculates average sale amount for each product.
select product_id, avg(amount_sold) avg_amount from sh.sales group by product_id;

-- 3 finds maximum and minimum sale amount for each product
select product_id, max(amount_sold) max_amount, min(amount_sold) min_amount from sh.sales group by product_id;

-- 4 cal total revenue generated by each product.(revenue = quantity sold * amount sold)
select product_id, (QUANTITY_SOLD * AMOUNT_SOLD) total_revenue from sh.sales group by product_id;

-- 5 counts number of sales transactions for each customer
select cust_id, count(*) no_of_sales from sh.sales group by cust_id;

-- 6,7,8 calculates average sale amount per customer,highest purchase amount for each customer, lowest purchase amount for each customer.    
select cust_id, avg(amount_sold) avg_sales, max(AMOUNT_SOLD) highest_purchase, min(AMOUNT_SOLD) lowest_purchase from sh.sales group by cust_id order by highest_purchase DESC,lowest_purchase ASC;

-- 13 Counts the number of sales per month. 
select extract(month from time_id) months,count(*) sales from sh.sales group by extract(month from time_id) order by months;